name: ustahub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.8
  provider: ^6.1.5+1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.3
  hive: ^2.2.3
  freezed_annotation: ^3.1.0
  dartz: ^0.10.1
  chopper: ^8.5.0
  rxdart: ^0.28.0
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  share_plus: ^12.0.1
  package_info_plus: ^9.0.0
  url_launcher: ^6.3.2
  sensors_plus: ^7.0.0
  connectivity_plus: ^7.0.0
  device_info_plus: ^12.3.0
  logger: ^2.6.2
  flutter_native_splash: ^2.4.7
  flutter_smart_dialog: ^4.9.8+9
  pull_to_refresh: ^2.0.0
  formz: ^0.8.0
  clarity_flutter: ^1.6.0

  firebase_core: ^4.3.0
  sms_autofill: ^2.4.1
  flutter_bloc: ^9.1.1
  built_collection: ^5.1.1
  flutter_animate: ^4.5.2
  flutter_multi_formatter: ^2.13.10
  flutter_xlider: ^3.5.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  flutter_spinkit: ^5.2.2
  cached_network_image: ^3.4.1
  animated_toggle_switch: ^0.8.5
  webview_flutter: ^4.13.0
  flutter_widget_from_html: ^0.17.1
  shimmer: ^3.0.0
  dio: ^5.9.0
  firebase_analytics: ^12.1.0
  facebook_app_events: ^0.24.0
  hive_flutter: ^1.1.0
  firebase_messaging: ^16.1.0
  flutter_timezone: ^5.0.1
  photo_view: ^0.15.0
  extended_image: ^10.0.1
  image_cropper: ^11.0.0
  image_picker: ^1.2.1
  appsflyer_sdk: ^6.17.8
  photo_manager: ^3.8.3
  photo_manager_image_provider: ^2.2.0
  camera: ^0.11.3
  timezone: ^0.10.1
  animated_visibility: ^0.0.4
  story_view: ^0.16.6
  built_value: ^8.12.1
  lottie: ^3.3.2
  smooth_page_indicator: ^2.0.1
  google_fonts: ^7.0.0
  curved_navigation_bar: ^1.0.6
  pinput: ^6.0.1
  shared_preferences: ^2.5.4
  bloc: ^9.2.0
  equatable: ^2.0.8
  pretty_dio_logger: ^1.4.0
  get_it: ^9.2.0
  path: ^1.9.1
  gap: ^3.0.1
  carousel_slider: ^5.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translation/
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/fonts/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
  min_sdk_android: 24
  remove_alpha_ios: true
